// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mr_shtrahman.Data;

namespace mr_shtrahman.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210622061942_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductShop", b =>
                {
                    b.Property<string>("ProductsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShopsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductsId", "ShopsId");

                    b.HasIndex("ShopsId");

                    b.ToTable("ProductShop");
                });

            modelBuilder.Entity("ProductTrip", b =>
                {
                    b.Property<string>("RelventProductsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TripsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RelventProductsId", "TripsId");

                    b.HasIndex("TripsId");

                    b.ToTable("ProductTrip");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Img", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Img");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImgId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("ImgId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNum")
                        .HasColumnType("int");

                    b.Property<short>("rating")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ImgId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClosestShopsId")
                        .HasColumnType("int");

                    b.Property<string>("ClosestShopsId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImgId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClosestShopsId1");

                    b.HasIndex("ImgId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("mr_shtrahman.Models.VisitorsAttendance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Attendance")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("TripId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TripId1");

                    b.ToTable("VisitorsAttendance");
                });

            modelBuilder.Entity("ProductShop", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mr_shtrahman.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTrip", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("RelventProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mr_shtrahman.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mr_shtrahman.Models.Product", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Img", "Img")
                        .WithMany()
                        .HasForeignKey("ImgId");

                    b.Navigation("Img");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Shop", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Img", "Img")
                        .WithMany()
                        .HasForeignKey("ImgId");

                    b.Navigation("Img");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Trip", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Shop", "ClosestShops")
                        .WithMany("Trips")
                        .HasForeignKey("ClosestShopsId1");

                    b.HasOne("mr_shtrahman.Models.Img", "Img")
                        .WithMany()
                        .HasForeignKey("ImgId");

                    b.Navigation("ClosestShops");

                    b.Navigation("Img");
                });

            modelBuilder.Entity("mr_shtrahman.Models.VisitorsAttendance", b =>
                {
                    b.HasOne("mr_shtrahman.Models.Trip", "Trip")
                        .WithMany("VisitorsAttendance")
                        .HasForeignKey("TripId1");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Shop", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("mr_shtrahman.Models.Trip", b =>
                {
                    b.Navigation("VisitorsAttendance");
                });
#pragma warning restore 612, 618
        }
    }
}
